### ISSUE TITLE
Those 2 are not regular variables

### ISSUE THREAD

**Issue by AlexKap23** [f-guevara/TilesCalGithubRepository#2]
https://github.com/f-guevara/TilesCalGithubRepository/blob/2f83d089cb4d5059fb77f0f5f98e880b1a40127d/TileCostCalculator/TileCostCalculator/Program.cs#L105-L106

Those 2 variables can be converted to constants, since their value is never changing. Convert them to constants and move them up top!

**Comment by f-guevara** [comment]
Closed
